### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by bbrendon** [vulogov/zq#6]
```
# pip3 install zq
Collecting zq
  Using cached zq-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bup6szcb/zq/setup.py", line 18
        print "CMake  is required to build zql"
                                              ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bup6szcb/zq/

```

**Comment by vulogov** [comment]
Thank you for trying. zq never been tested and ported to Python3. As of now, it is for Python2 only. If you are wiling to participate in the porting efforts, please let me know.
